### ISSUE TITLE
text changes

### ISSUE THREAD

**Issue by VenusCh001** [SnowScriptWinterOfCode/PortfolioCreations#116]
### Issue Description
(1) changing the text of the three subheadings
(2) the text is looking informal , planning to sound it professional 

### Expected Behavior
replacing _find me_ with **address**
replacing _call me_ with **contact number**
replacing _mail me_ with **email address**

### Actual Behavior
options are find ,call,contact me

### Screenshots (if relevant)
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/122210300/44805fe5-7b65-4983-8719-1323acdec777)

**Comment by Prriya-Karn** [comment]
please assign this issue to me

**Comment by PranjaliBhardwaj** [comment]
@Nitya-Pasrija @ayushichoudhary-19 Can you assign this issue to me?

**Comment by VenusCh001** [comment]
@ayushichoudhary-19

**Comment by VenusCh001** [comment]
@Nitya-Pasrija

**Comment by ayushichoudhary-19** [comment]
@VenusCh001 Thank you for raising these points. We appreciate your attention to detail and the effort to enhance the professionalism of the content.

However, we believe that the current wording ("Find Me," "Call Me," and "Mail Me") is intentional, providing a friendly and approachable tone and therefore we're not looking for any change in those.

Thank you for your understanding and collaboration.
